import IsingBulk.Tail.LeftSectorReciprocalJets
#print axioms IsingBulk.Tail.left_actual_sector_Z_gap
#print axioms IsingBulk.Tail.actual_compact_root_joint_jets
#print axioms IsingBulk.Tail.left_actual_frozen_Z_reciprocal_jets
